import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {LayoutDashboard,ClipboardList,PlusCircle,Users,ShieldCheck,BarChart3,Bell,Search,CheckCircle2,Clock3,XCircle,FileText,LogOut,Menu,ChevronRight,LockKeyhole,RefreshCw} from 'lucide-react';
import {supabase,supabaseConfigured} from './supabase';
import './styles.css';

const products=[
 {name:'Business',icon:'💼',desc:'SME & Enterprise Loans • Working Capital • Expansion'},
 {name:'Hire Purchase',icon:'🚗',desc:'Vehicle & Equipment Financing • Asset Purchase'},
 {name:'Personal',icon:'👤',desc:'Staff Personal Loan • Emergency • Lifestyle'},
 {name:'Baideshik Rojgar',icon:'✈️',desc:'Foreign Employment Loan • Migration Support • Visa Costs'},
 {name:'Agriculture',icon:'🌾',desc:'Farming • Seeds & Equipment • Seasonal Loan'}
];
const security=[['With Collateral','No Limit • Property / Gold / Asset • Lowest Interest','🔒'],['Without Collateral','Max 3 Lakh • Unsecured • Credit Based','🛡️'],['With Saving','Max 3 Lakh • Secured by Savings • Reduced Rate','🐷']];
const seed=[
 {id:'DEMO-1007',staff_name:'Sita Karki',product:'Personal',amount:250000,status:'Pending',created_at:'2026-10-07',stage:'Submitted'},
 {id:'DEMO-1006',staff_name:'Bikash Thapa',product:'Business',amount:750000,status:'Under Review',created_at:'2026-10-06',stage:'Risk Assessment'},
 {id:'DEMO-1005',staff_name:'Anil Joshi',product:'Hire Purchase',amount:420000,status:'Approved',created_at:'2026-10-05',stage:'Disbursal Ready'},
 {id:'DEMO-1004',staff_name:'Mina Gurung',product:'Personal',amount:150000,status:'Rejected with Reason',created_at:'2026-10-04',stage:'Notification Sent'}
];

function App(){
 const [session,setSession]=useState(null),[profile,setProfile]=useState(null),[loading,setLoading]=useState(true);
 useEffect(()=>{ if(!supabaseConfigured){setLoading(false);return;} supabase.auth.getSession().then(({data})=>{setSession(data.session); if(data.session) loadProfile(data.session.user.id); else setLoading(false)}); const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s); if(s) loadProfile(s.user.id); else {setProfile(null);setLoading(false)}}); return()=>subscription.unsubscribe(); },[]);
 async function loadProfile(id){const {data}=await supabase.from('profiles').select('*').eq('id',id).maybeSingle();setProfile(data||{full_name:session?.user?.email?.split('@')[0]||'Staff',role:'Loan Officer'});setLoading(false)}
 if(loading)return <div className="center">Loading Prarambha…</div>;
 if(!session)return <Login/>;
 return <Portal session={session} profile={profile} />;
}

function Login(){const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(e){e.preventDefault();setError('');if(!supabaseConfigured){setError('Supabase is not configured. Add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in Vercel.');return;}setBusy(true);const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setError(error.message);setBusy(false)}
 return <div className="loginpage"><div className="loginbox"><div className="brand loginbrand"><div className="logo"><ClipboardList size={25}/></div><div><b>Prarambha</b><span>Staff Loan Request System</span></div></div><h1>Staff Sign In</h1><p>Secure access for loan officers, reviewers and administrators.</p>{!supabaseConfigured&&<div className="warning">Supabase connection is not configured yet.</div>}{error&&<div className="error">{error}</div>}<form onSubmit={submit}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="staff@company.com" required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••" required/></label><button className="primary full" disabled={busy}>{busy?'Signing in…':'Sign In'} <ChevronRight size={17}/></button></form><small className="muted">Authentication is handled by Supabase Auth.</small></div></div>}

function Portal({session,profile}){const [page,setPage]=useState('Dashboard'),[sidebar,setSidebar]=useState(true),[requests,setRequests]=useState([]),[query,setQuery]=useState(''),[status,setStatus]=useState('All statuses'),[refreshing,setRefreshing]=useState(false);
 async function loadRequests(){setRefreshing(true); if(supabaseConfigured){const {data,error}=await supabase.from('loan_requests').select('*').order('created_at',{ascending:false}); if(!error)setRequests(data||[])} setRefreshing(false)}
 useEffect(()=>{loadRequests()},[]);
 const rows=requests.length?requests:seed; const filtered=useMemo(()=>rows.filter(r=>(`${r.staff_name||r.staff||''} ${r.request_code||r.id||''} ${r.product||''} ${r.status||''}`).toLowerCase().includes(query.toLowerCase())&&(status==='All statuses'||r.status===status)),[rows,query,status]);
 async function addRequest(payload){const local={...payload,id:'LOCAL-'+Date.now(),status:'Pending',stage:'Submitted',created_at:new Date().toISOString()}; if(!supabaseConfigured){setRequests([local,...requests]);setPage('Requests');return;} const {data,error}=await supabase.from('loan_requests').insert(payload).select().single(); if(error) throw error; setRequests([data,...requests]);setPage('Requests')}
 async function logout(){await supabase?.auth.signOut()}
 return <div className="app"><header className="top"><div className="brand"><div className="logo"><ClipboardList size={25}/></div><div><b>Prarambha</b><span>Staff Loan Request System</span></div></div><div className="topright"><span className="online"><i/> System Online</span><button className="iconbtn"><Bell size={19}/></button><div className="user"><div className="avatar">{(profile?.full_name||'LO').slice(0,2).toUpperCase()}</div><div><b>{profile?.full_name||session.user.email}</b><small>{profile?.role||'Loan Officer'}</small></div></div><button className="logout" onClick={logout}><LogOut size={16}/></button></div></header>
 <div className="body"><aside className={sidebar?'side':'side collapsed'}><button className="menubtn" onClick={()=>setSidebar(!sidebar)}><Menu size={20}/></button>{[['Dashboard',LayoutDashboard],['Requests',ClipboardList],['New Request',PlusCircle],['Staff',Users],['Workflow',ShieldCheck],['Reports',BarChart3]].map(([n,I])=><button key={n} className={'nav '+(page===n?'active':'')} onClick={()=>setPage(n)}><I size={19}/><span>{n}</span></button>)}<div className="sidebottom"><LockKeyhole size={17}/><span>Supabase RLS secured</span></div></aside>
 <main className="main"><div className="pagehead"><div><div className="crumb">Staff Loan Portal <ChevronRight size={14}/> {page}</div><h1>{page}</h1><p>{page==='Dashboard'?'Real-time overview of staff loan requests and workflow.':page==='Requests'?'Search, review and track every loan request.':page==='New Request'?'Create a new staff loan request.':'Roadmap module ready for implementation.'}</p></div>{page==='Requests'&&<button className="primary" onClick={()=>setPage('New Request')}><PlusCircle size={17}/> New Request</button>}</div>
 {page==='Dashboard'&&<Dashboard requests={rows} setPage={setPage}/>} {page==='Requests'&&<Requests rows={filtered} query={query} setQuery={setQuery} status={status} setStatus={setStatus} refresh={loadRequests} refreshing={refreshing}/>} {page==='New Request'&&<NewRequest onSubmit={addRequest}/>} {['Staff','Workflow','Reports'].includes(page)&&<Placeholder page={page}/>}</main></div></div>}
function Dashboard({requests,setPage}){const counts={Pending:requests.filter(x=>x.status==='Pending').length,'Under Review':requests.filter(x=>x.status==='Under Review').length,Approved:requests.filter(x=>x.status==='Approved').length,'Rejected with Reason':requests.filter(x=>x.status==='Rejected with Reason').length};return <><div className="stats"><Stat icon={<Clock3/>} label="Pending" value={counts.Pending} note="Awaiting review"/><Stat icon={<Search/>} label="Under Review" value={counts['Under Review']} note="Risk assessment"/><Stat icon={<CheckCircle2/>} label="Approved" value={counts.Approved} note="Ready for disbursal"/><Stat icon={<XCircle/>} label="Rejected" value={counts['Rejected with Reason']} note="Reason logged"/></div><section className="grid2"><div className="card"><div className="cardtitle"><div><b>5 Loan Products</b><small>Available request categories</small></div><button className="link" onClick={()=>setPage('New Request')}>Create <ChevronRight size={15}/></button></div><div className="productgrid">{products.map(p=><div className="product" key={p.name}><span>{p.icon}</span><div><b>{p.name}</b><small>{p.desc}</small></div></div>)}</div></div><div className="card"><div className="cardtitle"><div><b>3 Security Types</b><small>Policy controls</small></div><ShieldCheck size={22}/></div>{security.map(s=><div className="security" key={s[0]}><span>{s[2]}</span><div><b>{s[0]}</b><small>{s[1]}</small></div></div>)}</div></section><section className="card workflow"><div className="cardtitle"><div><b>4 Status Flow</b><small>From submission to decision</small></div><span className="badge">Live tracking</span></div><div className="flow">{[['Pending','Submitted'],['Under Review','Document Verification • Risk Assessment'],['Approved','Loan Sanctioned • Disbursal Ready'],['Rejected with Reason','Not Eligible • Reason Logged • Notification Sent']].map((x,i)=><div className="flowitem" key={x[0]}><div className={'flowicon f'+i}>{i===0?<Clock3/>:i===1?<Search/>:i===2?<CheckCircle2/>:<XCircle/>}</div><div><b>{x[0]}</b><small>{x[1]}</small></div>{i<3&&<div className="line"/>}</div>)}</div></section><section className="card"><div className="cardtitle"><div><b>Recent Requests</b><small>Audit-friendly request activity</small></div><button className="link" onClick={()=>setPage('Requests')}>View all <ChevronRight size={15}/></button></div><Table rows={requests.slice(0,4)}/></section></>}
function Stat({icon,label,value,note}){return <div className="stat"><div className="staticon">{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{note}</small></div></div>}
function Requests({rows,query,setQuery,status,setStatus,refresh,refreshing}){return <section className="card"><div className="toolbar"><div className="search"><Search size={18}/><input placeholder="Search ID, staff, product or status..." value={query} onChange={e=>setQuery(e.target.value)}/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option>All statuses</option><option>Pending</option><option>Under Review</option><option>Approved</option><option>Rejected with Reason</option></select><button className="iconbtn" onClick={refresh} title="Refresh"><RefreshCw size={17} className={refreshing?'spin':''}/></button></div><Table rows={rows}/></section>}
function Table({rows}){return <div className="tablewrap"><table><thead><tr><th>Request</th><th>Staff</th><th>Product</th><th>Amount</th><th>Status</th><th>Stage</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><b>{r.request_code||r.id}</b><small>{new Date(r.created_at).toLocaleDateString()}</small></td><td>{r.staff_name||r.staff}</td><td>{r.product}</td><td>Rs. {Number(r.amount).toLocaleString()}</td><td><span className={'status '+String(r.status).toLowerCase().replaceAll(' ','-')}>{r.status}</span></td><td>{r.stage}</td></tr>)}</tbody></table></div>}
function NewRequest({onSubmit}){const [busy,setBusy]=useState(false),[error,setError]=useState('');async function submit(e){e.preventDefault();setError('');setBusy(true);const f=new FormData(e.currentTarget);try{await onSubmit({staff_name:f.get('staff'),product:f.get('product'),amount:Number(f.get('amount')),security_type:f.get('security_type'),purpose:f.get('purpose')});e.currentTarget.reset()}catch(err){setError(err.message)}setBusy(false)}return <section className="card formcard"><div className="cardtitle"><div><b>New Staff Loan Request</b><small>Phase 2 • Dynamic application form</small></div><FileText size={23}/></div>{error&&<div className="error">{error}</div>}<form onSubmit={submit}><div className="formgrid"><label>Staff name<input name="staff" required placeholder="e.g. Sita Karki"/></label><label>Loan product<select name="product">{products.map(p=><option key={p.name}>{p.name}</option>)}</select></label><label>Requested amount<input name="amount" type="number" min="1000" required placeholder="250000"/></label><label>Security type<select name="security_type"><option>Without Collateral</option><option>With Collateral</option><option>With Saving</option></select></label><label className="wide">Purpose<textarea name="purpose" required placeholder="Explain the purpose of the loan..."/></label></div><div className="formfooter"><span><ShieldCheck size={16}/> Supabase validation + RLS protection</span><button className="primary" type="submit" disabled={busy}>{busy?'Submitting…':'Submit Request'} <ChevronRight size={17}/></button></div></form></section>}
function Placeholder({page}){return <section className="empty card"><div className="emptyicon">{page==='Staff'?<Users/>:page==='Workflow'?<ShieldCheck/>:<BarChart3/>}</div><h2>{page} module</h2><p>This module is the next implementation area: role-based access, approval rules, audit history, notifications, exports and analytics.</p><div className="road"><span>Phase 1 ✓</span><span>Phase 2 ✓</span><span>Phase 3 →</span><span>Phase 4 →</span><span>Phase 5 →</span></div></section>}
createRoot(document.getElementById('root')).render(<App/>);
